// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB-_j5wc3tuekk4VTGAi5EL7IjNM-Md0iw',
    appId: '1:191982719239:web:b79779076ff0865d2df5a2',
    messagingSenderId: '191982719239',
    projectId: 'learning-app-3a453',
    authDomain: 'learning-app-3a453.firebaseapp.com',
    storageBucket: 'learning-app-3a453.appspot.com',
    measurementId: 'G-7LKMQL9J2E',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyClHZgKAvFflJ1_eGxZgtpr1cMP1S1sj_0',
    appId: '1:191982719239:android:2db98dd038f194952df5a2',
    messagingSenderId: '191982719239',
    projectId: 'learning-app-3a453',
    storageBucket: 'learning-app-3a453.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBCUL9c2GKMZSv68brSgD4QlsWFdGGTbNo',
    appId: '1:191982719239:ios:533d62a5a910aaa12df5a2',
    messagingSenderId: '191982719239',
    projectId: 'learning-app-3a453',
    storageBucket: 'learning-app-3a453.appspot.com',
    iosBundleId: 'com.example.learningApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBCUL9c2GKMZSv68brSgD4QlsWFdGGTbNo',
    appId: '1:191982719239:ios:533d62a5a910aaa12df5a2',
    messagingSenderId: '191982719239',
    projectId: 'learning-app-3a453',
    storageBucket: 'learning-app-3a453.appspot.com',
    iosBundleId: 'com.example.learningApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB-_j5wc3tuekk4VTGAi5EL7IjNM-Md0iw',
    appId: '1:191982719239:web:dbd2591709ce85572df5a2',
    messagingSenderId: '191982719239',
    projectId: 'learning-app-3a453',
    authDomain: 'learning-app-3a453.firebaseapp.com',
    storageBucket: 'learning-app-3a453.appspot.com',
    measurementId: 'G-NRDYTW4XDQ',
  );
}
